config/routes.rb
Escolinha::Application.routes.draw do
   root :to => "page#home"

   resources :teachers
   resources :courses
   resources :disciplines  
   resources :rooms
   resources :students

   get '/testes' => "courses#list"
end

app/models/adapter_specific.rb
class AdapterSpecific
   class << self

      def like_case_insensitive
         case ActiveRecord::Base.connection.adapter_name
            when 'PostgreSQL'
               'ILIKE'
            else
               'LIKE'
            end
         end
      end
end

app/models/course.rb
class Course < ActiveRecord::Base
   extend FriendlyId

   attr_accessible :name

   has_many :students   
   has_many :rooms

   validates_presence_of :name
   validates_uniqueness_of :name

   friendly_id :name, :use => :slugged

   def self.search(query,page)
      if query.present?         
         joins("LEFT JOIN rooms on rooms.course_id = courses.id LEFT JOIN teachers on rooms.teacher_id = teachers.id").         
         where(["courses.name #{AdapterSpecific.like_case_insensitive} :query OR teachers.name #{AdapterSpecific.like_case_insensitive} :query", :query => "%#{query}%"]).group("courses.id").order("courses.name")
      else         
         paginate :page => page, :size => 8
      end
   end
end

app/models/discipline.rb
class Discipline < ActiveRecord::Base
   extend FriendlyId
   
   attr_accessible :name

   validates_presence_of :name   

   has_many :rooms
   has_many :teachers, :through => :rooms

   friendly_id :name, :use => :slugged
end

app/models/room.rb
class Room < ActiveRecord::Base
   attr_accessible :course_id, :teacher_id, :discipline_id

   belongs_to :course
   belongs_to :teacher
   belongs_to :discipline

   validates_presence_of :course, :teacher, :discipline
end

app/models/student.rb
#encoding: UTF-8
class Student < ActiveRecord::Base
   extend FriendlyId

   attr_accessible :name, :email, :course_id

   belongs_to :course #:counter_cache => true

   validates_presence_of :name, :email
   validates_uniqueness_of :email

   friendly_id :name, :use => :slugged
end

app/models/teacher.rb
class Teacher < ActiveRecord::Base
   extend FriendlyId

	attr_accessible :name, :picture

	validates_presence_of :name

   mount_uploader :picture, PictureUploader
   friendly_id :name, :use => :slugged

   has_many :rooms
   has_many :disciplines, :through => :rooms

   def thumb_url
      self.picture.thumb.url
   end

   def has_picture
      self.picture?
   end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
   def index
      @search_query = params[:q]
      page         = params[:page]

      @courses = Course.search(@search_query, page)
   end   

   def new
      @course = Course.new
   end

   def show
      @course = Course.find params[:id]      

      @disciplines_teachers  = Room.where("course_id = ?", @course.id)
   end

   def create
      @course = Course.new params[:course]

      if @course.save
         flash[:notice] = t("flash.courses.create.notice")
         redirect_to courses_path
      else
         render :new
      end
   end

   def edit
      @course = Course.find params[:id]      
   end

   def update
      @course = Course.find params[:id]
      if @course.update_attributes params[:course]
         flash[:notice] = t("flash.courses.update.notice")
         redirect_to courses_path
      else
         render :edit
      end
   end
end

app/controllers/disciplines_controller.rb
class DisciplinesController < ApplicationController
   def index
      @disciplines = Discipline.paginate :page => params[:page], :size => 10
   end

   def new
      @discipline = Discipline.new
   end

   def create
      @discipline = Discipline.new params[:discipline]

      if @discipline.save
         flash[:notice] = t("flash.disciplines.create.notice")
         redirect_to disciplines_path
      else
         render :new
      end
   end

   def edit
      @discipline = Discipline.find params[:id]
   end

   def update
      @discipline = Discipline.find params[:id]

      if @discipline.update_attributes params[:discipline]
         redirect_to disciplines_path
         flash[:notice] = t("flash.disciplines.update.notice")
      else
         render :edit
      end
   end
end

app/controllers/page_controller.rb
class PageController < ApplicationController
	def home
	end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController

   #Load dropdown    
   helper_method :teachers, :courses, :disciplines

   def new
      @room = Room.new
   end

   def create
      @room = Room.new params[:room]

      if @room.save
         flash[:notice] = "Dados enviados com sucesso!"
         redirect_to course_path(@room.course)
      else
         render :new
      end
   end

   def destroy
      @room = Room.find params[:id]
      @room.destroy

      redirect_to courses_path
   end

   def teachers
      Teacher.order(:name)
   end

   def courses
      Course.order(:name)
   end

   def disciplines
      Discipline.order(:name)
   end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController

   helper_method :courses

   def index
      @students = Student.paginate :page => params[:page], :size => 10
   end   

   def new
      @student = Student.new
   end

   def create
      @student = Student.new params[:student]

      if @student.save
         flash[:notice] = t("flash.students.create.notice")

         MatriculandoMailer.email_do_matriculado(@student).deliver

         redirect_to students_path
      else
         render :new
      end
   end

   def edit
      @student = Student.find(params[:id])
   end

   def update
      @student = Student.find params[:id]

      if @student.update_attributes params[:student]
         flash[:notice] = t("flash.students.update.notice")
         redirect_to students_path
      else
         render :edit
      end
   end

   def courses
      Course.order(:name)
   end
end

app/controllers/teachers_controller.rb
class TeachersController < ApplicationController
   def index
      @teachers = Teacher.paginate :page => params[:page], :size => 10
   end

   def show
      @teacher = Teacher.find params[:id]      

      @rooms = Room.select("discipline_id, course_id").where("teacher_id = ?", @teacher.id)
   end

   def new
      @teacher = Teacher.new
   end

   def create
      @teacher = Teacher.new params[:teacher]      

      if @teacher.save
         flash[:notice] = t("flash.teachers.create.notice")
         redirect_to teachers_path
      else
         render :new
      end
   end

      def edit
         @teacher = Teacher.find params[:id]      
      end

      def update
         @teacher = Teacher.find params[:id]

         if @teacher.update_attributes params[:teacher]
            flash[:notice] = t("flash.teachers.update.notice")
            redirect_to teachers_path
         else
            render :edit
         end
      end
end

app/helpers/application_helper.rb
module ApplicationHelper
   
end

app/views/courses/_form.html.erb
<%= simple_form_for @course do |f| %>

   <%= render "shared/error_messages", :record => @course %>

   <p>      
      <%= f.input :name %>
   </p>

   <p>
      <%= f.button :submit %>
   </p>
   
<% end %>

app/views/courses/_search.html.erb
<p>
   <%= form_tag "", :method => :get, :class => "search_form" do %>
      <%= t("form.search.label") %>
      <%= text_field_tag :q, @query_search, :placeholder => t("form.search.for") %>      
   <% end %>   
</p>

app/views/courses/edit.html.erb
<h3>Editar turma</h3>

<%= render "form" %>

app/views/courses/index.html.erb
<h3>
   <% if @search_query.present? %>
      <%= t("page.search_result") %>
   <% else %>
      <%= t("page.title") %>
   <% end %>
</h3>

<%= render "search" %>


<p>
   <%= link_to t("nav.link.courses.register"), new_course_path %>
</p>

<% unless @courses.empty? %>
   <table class="table">
      <tr>
         <th>Nome</th>
         <th></th>
      </tr>

      <% @courses.each do |course| %>

         <tr>
            <td><%= course.name %></td>
            <td><%= link_to(t("helpers.link.course.show"), course_path(course))%></td>
            <td><%= link_to(t("helpers.link.course.edit"), edit_course_path(course))%></td>
         </tr>         

         <tr>
            <% course.rooms.each do |c| %>
                  <td style="font-size:10px;border: 1px solid #98BF21; background-color: #98BF45;font-weight:bold">
                     <%= "#{c.teacher.name} ministrando #{c.discipline.name}" %>
                  </td>
            <% end %>
         </tr>

      <% end %>
   </table>
<% else %>
   <%= t("page.list.without.text") %>
<% end %>

<p>
   <% unless @courses.empty? %>
      <%= paginate @courses, :size => 8 %>
   <% end %>
</p>

app/views/courses/new.html.erb
<h3>Cadastrar Turma</h3>

<%= render "form" %>

app/views/courses/show.html.erb
<h3>
   <%= @course.name %>
</h3>


<section class="box">
<h4>Disciplinas</h4>

   <% unless @disciplines_teachers.empty? %>

   <dl>
      <% @disciplines_teachers.each do |room| %>

         <dt><%= room.discipline.name %><small> ministrado(a) por </small><%= room.teacher.name %></dt>

         <dd>
            <small>
               <%=link_to "Remover", room ,method: :delete,
               data: {confirm: "confirmar remoção ?"} %>   
            </small>
         </dd>

      <% end %>
   </dl>

   <% else %>

      Nenhum registro!

   <% end %>
</section>


<section class="box">
<h4>Alunos</h4>

<% unless @course.students(true).empty? %>
   <dl>

      <% @course.students.each do |student| %>
         <dt>
            <%= student.name %>
         </dt>

           <dd>
            <small>
               <%=link_to "Alterar", edit_student_path(student) %>   
            </small>
         </dd>
      <% end %>      
   </dl>

<% else %>

   Nenhum registro!

<% end %>

</section>

app/views/disciplines/_form.html.erb
<%= simple_form_for @discipline do |f| %>

   <%= render "shared/error_messages", :record => @discipline %>

   <p>      
      <%= f.input :name, requered: true %>
   </p>

   <p>
      <%= f.button :submit %>
   </p>
<% end %>

app/views/disciplines/edit.html.erb
<h3>Editar disciplina</h3>

<%= render "form" %>

app/views/disciplines/index.html.erb
<h3>Disciplinas Cadastradas</h3>

<p>
   <%= link_to t("nav.link.disciplines.register"), new_discipline_path %>
</p>

<% unless @disciplines.empty? %>
   <table class="table">
      <tr>
         <th>Nome</th>
         <th></th>
      </tr>

      <% @disciplines.each do |discipline| %>
         <tr>
            <td><%= discipline.name %></td>
            <td><%= link_to(t("helpers.link.discipline.edit"), edit_discipline_path(discipline))%></td>
         </tr>
      <% end %>
   </table>
<% else %>
   <%= t("page.list.without.text") %>
<% end %>
<p>
   <%= paginate @disciplines, :size => 10 %>
</p>

app/views/disciplines/new.html.erb
<h3>Cadastrar disciplina</h3>

<%= render "form" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>..:: Escolinha ::..</title>
  <%= stylesheet_link_tag  "application","simple_form", :media => "all" %>
  <%= javascript_include_tag(:defaults) %>
  <%= csrf_meta_tags %>
</head>

<body>
<div class="shell">
  <div class="border">
    <div id="header">      
      
    <div id="navigation">
      <%= render "shared/nav" %>
      <div class="cl">&nbsp;</div>
    </div>

    <div id="main">
      <div id="content" class="left">
        <div class="highlight">

             <%= render "shared/flash_messages" %>        
             <%= yield %>
             
        </div>
      </div>
      <div class="cl">&nbsp;</div>
    </div>    

    <div class="shadow-l"></div>
    <div class="shadow-r"></div>
    <div class="shadow-b"></div>

  </div>

  <div id="footer">    
    <div class="cl"></div>
  </div>
  
</div>

<%= javascript_include_tag "application" %>
</body>
</html>

app/views/page/home.html.erb
<h1><%= t("page.home")%></h1>

<p>
   Secção 1.10.32 do "de Finibus Bonorum et Malorum", escrito por Cícero em 45 AC.

   "Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem. Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur? Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur, vel illum qui dolorem eum fugiat quo voluptas nulla pariatur?"
</p>

app/views/rooms/new.html.erb
<h3>Montar Sala</h3>

<%= simple_form_for @room do |f| %>     

   <%= render "shared/error_messages", :record => @room %>

   <p>      
      <%= f.input :course_id, collection: courses, required: true %>
   </p>

   <p>      
      <%= f.input :teacher_id, collection: teachers, required: true %>
   </p>

   <p>      
      <%= f.input :discipline_id, collection: disciplines, required: true %>      
   </p>

   <p>
      <%= f.button :submit %>
   </p>

<% end %>

app/views/shared/_error_messages.html.erb
<p>
   <% unless record.errors.empty? %>
   <%= t("form.error_messages") %>

      <dl class="alert">      
         <% record.errors.full_messages.each do |message| %>
            <dd><%= message %></dd>
         <% end %>
      </dl>
      
   <% end %>
</p>

app/views/shared/_flash_messages.html.erb
<% flash.each do |type, message| %>
   <p class="<%= type%>"><%= message %></p>
<% end %>

app/views/shared/_nav.html.erb
<ul>
   <li><%= link_to t("nav.link.courses.list"), courses_path %></li>
   <li><%= link_to t("nav.link.students.list"), students_path %></li>
   <li><%= link_to t("nav.link.disciplines.list"), disciplines_path %></li>
   <li><%= link_to t("nav.link.teachers.list"), teachers_path %></li>
   <li><%= link_to t("nav.link.rooms.new"), new_room_path %></li>
</ul>

app/views/students/_form.html.erb
<%= simple_form_for @student do |f| %>

   <%= render "shared/error_messages", :record => @student %>

   <p>
      <%= f.input :name, required: true%>
   </p>

   <p>
      <%= f.input :email, required: true%>
   </p>
   
   <p>
      <%= f.input :course_id, collection: courses  %>
   </p>
   
   <p>
      <%= f.button :submit %>   
   </p>
   
<% end %>

app/views/students/edit.html.erb
<h3>Editar aluno</h3>

<%= render "form" %>

app/views/students/index.html.erb
<h3>Alunos Cadastrados</h3>

<p>
   <%= link_to t("nav.link.students.register"), new_student_path %>
</p>

<% unless @students.empty? %>
   <table class="table">
      <tr>
         <th>Nome</th>
         <th></th>
      </tr>

      <% @students.each do |student| %>
         <tr>
            <td><%= student.name %></td>
            <td><%= link_to(t("helpers.link.student.edit"), edit_student_path(student))%></td>
         </tr>
      <% end %>
   </table>
<% else %>
   <%= t("page.list.without.text") %>
<% end %>   

<p>
   <%= paginate @students, :size => 10 %>
</p>

app/views/students/new.html.erb
<h3>Cadastrar aluno</h3>

<%= render "form" %>

app/views/teachers/_form.html.erb
<%= simple_form_for @teacher do |f| %>

   <%= render "shared/error_messages", :record => @teacher %>

   <p>
      <% if @teacher.has_picture %>
         <%= image_tag(@teacher.thumb_url)  %>         
         <% text = "Mudar foto:" %>
      <% else %>
         <% text = "Inserir foto:" %>
      <% end %>
      <br />
      <%= f.label "#{text}" %>
      <%= f.file_field :picture %>
   </p>

   <p>      
      <%= f.input :name, requered: true %>
   </p>

   <p>
      <%= f.button :submit %>
   </p>

<% end %>

app/views/teachers/edit.html.erb
<h3>Editar professor</h3>
<%= render "form" %>

app/views/teachers/index.html.erb
<h3>Professores Cadastrados</h3>

<p>
   <%= link_to t("nav.link.teachers.register"), new_teacher_path %>
</p>

<% unless @teachers.empty? %>

   <table class="table">
      <tr>
         <th>Nome</th>
         <th></th>
         <th></th>
      </tr>

      <% @teachers.each do |teacher| %>
         <tr>
            <td><%= teacher.name %></td>
            <td><%= link_to(t("helpers.link.teacher.show"), teacher_path(teacher))%></td>
            <td><%= link_to(t("helpers.link.teacher.edit"), edit_teacher_path(teacher))%></td>
         </tr>
      <% end %>
   </table>

<% else %>
<%= t("page.list.without.text") %>
<% end%>


<p>
   <%= paginate @teachers, :size => 10 %>
</p>

app/views/teachers/new.html.erb
<h3>Cadastrar professor</h3>
<%= render "form" %>

app/views/teachers/show.html.erb
<% if @teacher.has_picture %>
   <%= image_tag(@teacher.thumb_url) %>
<% else %>   
   <%= link_to(t("helpers.link.teacher.picture"), edit_teacher_path(@teacher)) %>
<% end %>   

<h2>
   <%= @teacher.name %>
</h2>